name: BetterServer
version: 1.21.101
main: floxy\BetterServer\Main
api: 5.0.0
src-namespace-prefix: floxy\BetterServer

commands:
 bettersrv.restart:
  description: Restart the Server
  permission: betterserver.restart
  
 bettersrv.reload:
  description: Reload the Plugin
  permission: betterserver.reload
  
permissions:
 betterserver.restart:
  default: false
 betterserver.reload:
  default: op
